leftnav:
- identifier: 88b3fb88-b8b9-6f78-97bd-74441f7dde51
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: c40b08b7-3e7e-5b6a-3961-e255d8084748
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: c0be9473-719d-0eb1-7f2f-3b02b6e18597
  name: Assignments
  pageRef: /pages/assignments
  weight: 30
